name: pdf_viewer_app
description: PDF Viewer App (User + Admin Panel)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0-nullsafety.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1

  # Network
  http: ^1.2.1

  # File picking
  file_picker: 8.1.7

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^31.2.15

  # Save & open file
  path_provider: ^2.1.5
  open_filex: ^4.5.0

  # Share intent
  receive_sharing_intent: ^1.8.1

  # Device info
  device_info_plus: 12.2.0
  shared_preferences: ^2.2.3

  syncfusion_flutter_pdf: ^31.2.15
  image_picker: ^1.1.2

  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true